export const ROUTES = {
  Main: "/",
  QuizzesList: "/quizzes",
  Quiz: (pseudoId) => (pseudoId ? `/quizzes/${pseudoId}` : "/quizzes/:pseudoId"),
  QuizStats: (pseudoId) =>  (pseudoId ? `/quizzes/${pseudoId}/stats` : "/quizzes/:pseudoId/stats"),
  PlayQuiz: (pseudoId) =>  (pseudoId ? `/quizzes/${pseudoId}/play` : "/quizzes/:pseudoId/play"),
  Login: "/login",
  Signup: "/signup",
  Profile: (nickname) => (nickname ? `/user/${nickname}` : "/user/:nickname"),
  Privacy: (nickname) => (nickname ? `/user/${nickname}/privacy` : "/user/:nickname/privacy"),
  User_completed_quizzes: (nickname) => (nickname ? `/user/${nickname}/quizzes/completed` : "/user/:nickname/quizzes/completed"),
  User_quizzes: (nickname) => (nickname ? `/user/${nickname}/quizzes/my` : "/user/:nickname/quizzes/my"),
  User_wishlisted_quizzes: (nickname) => (nickname ? `/user/${nickname}/quizzes/wishlist` : "/user/:nickname/quizzes/wishlist"),
  About: "/about",
  Contacts: "/contacts",

  Facebook: "https://www.facebook.com/groups/304790906885280/",
  Instagram: "https://www.instagram.com/kotenko_ppp/",
  LinkedIn: "https://www.linkedin.com/in/ілля-котенко-b26519214/",
  X: "https://x.com/CounterStrike",
}